# Generated by Django 4.1.5 on 2023-03-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
